name: Open with WebStorm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Open with WebStorm
        run: |
          echo "Opening with WebStorm..."
          C:\Program Files\JetBrains\WebStorm 2023.1.3\bin\webstorm64.exe --idea.config.path $HOME/.webstorm2023.2/config
          C:\Program Files\JetBrains\WebStorm 2023.1.3\bin\webstorm64.exe $GITHUB_WORKSPACE
